name: Update Amnezia List

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:      # Allows you to click "Run Now" manually

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write     # Required to push changes back to repo

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Run Generator
      run: php generate.php

    - name: Commit and Push if changed
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Auto-update Iran IP list"
        file_pattern: 'iran-routes.json'
